pipeline:

  my-build:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs_serenity_automation .
    when:
      branch: master
      event: push

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-serenity-automation quay.io/ukhomeofficedigital/hocs-serenity-automation:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-serenity-automation:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-serenity-automation quay.io/ukhomeofficedigital/hocs-serenity-automation:latest
      - docker push quay.io/ukhomeofficedigital/hocs-serenity-automation:latest
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-serenity-automation quay.io/ukhomeofficedigital/hocs-serenity-automation:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/hocs-serenity-automation:$${DRONE_TAG}
    when:
      event: tag

