pipeline:

  my-build:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs_serenity_automation .
      - docker run hocs_serenity_automation
    when:
      branch: master
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+hocs
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/hocs-serenity-automation
    tags:
      - build-${DRONE_BUILD_NUMBER}
      - latest
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-serenity-automation quay.io/ukhomeofficedigital/hocs-serenity-automation:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/hocs-serenity-automation:$${DRONE_TAG}
    when:
      event: tag

  execute-tests:
    image: quay.io/ukhomeofficedigital/hocs-serenity-automation
    secrets:
       - artifactory_username
       - artifactory_password
    commands:
      - sh bin/smoke-tests.sh
    when:
      branch: master
      event: push

  upload-serenity-report:
    image: plugins/s3
    settings:
      bucket: ${S3_BUCKET_NAME}
      access_key:
        from_secret: S3_ACCESS_KEY
      secret_key:
        from_secret: S3_SECRET_KEY
      source: target/site/serenity/*.html
      target: /${DRONE_BUILD_NUMBER}/report/
      when:
        branch: master
        event: push

services:
  selenium:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
      DISPLAY: ":99.0"

  firefox:
    image: selenium/node-firefox
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
      DISPLAY: ":98.0"